- type: tile
  editorHidden: false
  id: ClassicStonebricks
  name: classic-tiles-stonebricks
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStonebricks

- type: tile
  editorHidden: false
  id: ClassicStonebricksSnowed
  name: classic-tiles-stonebricks
  sprite: /Textures/_Classic/Tiles/Stonebricks/snowstonebricks.png
  variants: 9
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStonebricks

- type: tile
  editorHidden: false
  id: ClassicStonebricksSmallCarved1
  name: classic-tiles-stonebricks-small-carved1
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_small_carved_1.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStonebricksSmallCarved

- type: tile
  editorHidden: false
  id: ClassicStonebricksSmallCarved2
  name: classic-tiles-stonebricks-small-carved2
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_small_carved_2.png
  variants: 1
  placementVariants:
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStonebricksSmallCarved2

- type: tile
  editorHidden: false
  id: ClassicStoneLongBricks
  name: classic-tiles-stonebricks-long-bricks
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_long.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneLongBricks

- type: tile
  editorHidden: false
  id: ClassicStoneMediumBricks
  name: classic-tiles-stonebricks-medium
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_medium.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneMediumBricks

- type: tile
  editorHidden: false
  id: ClassicStoneDiamond
  name: classic-tiles-stonebricks-diamond
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_diamond.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneDiamond

- type: tile
  editorHidden: false
  id: ClassicStoneSquarePattern
  name: classic-tiles-stonebricks-square-pattern
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_square_pattern.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneSquarePattern

- type: tile
  editorHidden: false
  id: ClassicStoneMediumCircles
  name: classic-tiles-stonebricks-medium-circles
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_medium_circles.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneMediumCircles

- type: tile
  editorHidden: false
  id: ClassicStoneSmallCircles
  name: classic-tiles-stonebricks-small-circles
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_small_circles.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStoneSmallCircles

- type: tile
  editorHidden: false
  id: ClassicStonebricksSquareCarved
  name: classic-tiles-stonebricks-square-carved
  sprite: /Textures/_Classic/Tiles/Stonebricks/stonebricks_square_carved.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  edgeSpritePriority: 101
  edgeSprites:
    SouthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_SE.png
    NorthEast: /Textures/_Classic/Tiles/Stonebricks/single_edge_NE.png
    NorthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_NW.png
    SouthWest: /Textures/_Classic/Tiles/Stonebricks/single_edge_SW.png
    South: /Textures/_Classic/Tiles/Stonebricks/double_edge_S.png
    East: /Textures/_Classic/Tiles/Stonebricks/double_edge_E.png
    North: /Textures/_Classic/Tiles/Stonebricks/double_edge_N.png
    West: /Textures/_Classic/Tiles/Stonebricks/double_edge_W.png
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileStonebricksSquareCarved

- type: tile
  editorHidden: false
  id: ClassicGlass
  name: classic-tiles-glass
  sprite: /Textures/_Classic/Tiles/glass.png
  variants: 1
  placementVariants:
  - 1.0
  baseTurf: Space
  isSubfloor: true
  footstepSounds:
    collection: FootstepTile
  heatCapacity: 10000
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileGlass
  transparent: true
  weather: true

- type: tile
  editorHidden: false
  id: ClassicRoofRed
  name: classic-tiles-roof
  sprite: /Textures/_Classic/Tiles/roof_red.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileRoofRed

- type: tile
  editorHidden: false
  id: ClassicRoofGreen
  name: classic-tiles-roof
  sprite: /Textures/_Classic/Tiles/roof_green.png
  variants: 4
  placementVariants:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
  baseTurf: ClassicPlanks
  isSubfloor: false
  footstepSounds:
    collection: FootstepAsteroid
  heatCapacity: 10000
  weather: true
  deconstructTools: [ Prying ]
  itemDrop: ClassicFloorTileRoofGreen
