using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Starlight.Antags.Clockwork.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Starlight.Antags.Clockwork.UI;

[GenerateTypedNameReferences]
public sealed partial class EnchantMenu : RadialMenu
{
    [Dependency] private readonly IClyde _clyde = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    
    public event Action<BaseClockworkEnchantAction>? OnAiRadial;
    
    private EntityUid _tracked;

    public EnchantMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
    
    public void Track(EntityUid owner)
    {
        _tracked = owner;

        if (!_entManager.EntityExists(_tracked))
        {
            Close();
            return;
        }

        BuildButtons();
        UpdatePosition();
    }
    
    private void BuildButtons()
    {
        //var ev = new GetStationAiRadialEvent(); Needs action system(like condition)
        //_entManager.EventBus.RaiseLocalEvent(_tracked, ref ev);

        var main = FindControl<RadialContainer>("Main");
        main.DisposeAllChildren();
        var sprites = _entManager.System<SpriteSystem>();
    }
    
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdatePosition();
    }
    
    private void UpdatePosition()
    {
        if (!_entManager.TryGetComponent(_tracked, out TransformComponent? xform))
        {
            Close();
            return;
        }

        if (!xform.Coordinates.IsValid(_entManager))
        {
            Close();
            return;
        }

        var coords = _entManager.System<SpriteSystem>().GetSpriteScreenCoordinates((_tracked, null, xform));

        if (!coords.IsValid)
        {
            Close();
            return;
        }

        OpenScreenAt(coords.Position, _clyde);
    }
}