using System.Numerics;
using Content.Client.Resources;
using Content.Client.UserInterface.Controls;
using Content.Shared.Starlight.Antags.Clockwork.Components;
using Robust.Client.ResourceManagement;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using Robust.Shared.Graphics.RSI;

namespace Content.Client._Starlight.Antags.Clockwork.UI;

[GenerateTypedNameReferences]
public sealed partial class EnchantMenu : RadialMenu
{
    [Dependency] private readonly IClyde _clyde = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;
    
    public event Action<EntityUid>? OnItemSelected;
    
    private EntityUid _tracked;

    public EnchantMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }
    
    public void Track(EntityUid owner)
    {
        _tracked = owner;

        if (!_entManager.EntityExists(_tracked))
        {
            Close();
            return;
        }

        BuildButtons();
        UpdatePosition();
    }
    
    private void BuildButtons()
    {
        if (!_entManager.TryGetComponent<EnchantUserComponent>(_tracked, out var enchantUser))
            return;
        
        var main = FindControl<RadialContainer>("Main");
        main.DisposeAllChildren();
        var spriteSystem = _entManager.System<SpriteSystem>();
        
        foreach (var item in enchantUser.EntitiesToEnchant)
        {
            // Button
            var button = new EnchantMenuItemButton(item)
            {
                SetSize = new Vector2(64f, 64f),
            };
            
            
            // Texture
            if (_entManager.TryGetComponent<SpriteComponent>(item, out var spriteComp) && spriteComp.Icon?.GetFrame(RsiDirection.South, 0) is {} frame)
            {
                var texture = frame;
                var scale = Vector2.One;
                
                if (texture.Width <= 32)
                    scale *= 2;
                
                var rect = new TextureRect
                {
                    VerticalAlignment = VAlignment.Center,
                    HorizontalAlignment = HAlignment.Center,
                    Texture = texture,
                    TextureScale = scale,
                };

                button.AddChild(rect);
            }
            
            // Event
            button.OnPressed += args =>
            {
                OnItemSelected?.Invoke(item);
                Close();
            };
            
            main.AddChild(button);
        }
    }
    
    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdatePosition();
    }
    
    private void UpdatePosition()
    {
        if (!_entManager.TryGetComponent(_tracked, out TransformComponent? xform))
        {
            Close();
            return;
        }

        if (!xform.Coordinates.IsValid(_entManager))
        {
            Close();
            return;
        }

        var coords = _entManager.System<SpriteSystem>().GetSpriteScreenCoordinates((_tracked, null, xform));

        if (!coords.IsValid)
        {
            Close();
            return;
        }

        OpenScreenAt(coords.Position, _clyde);
    }
}

public sealed class EnchantMenuItemButton(EntityUid item) : RadialMenuTextureButtonWithSector
{
    public EntityUid Item = item;
}