using Content.Server.Parallax;
using Content.Shared.Parallax.Biomes;
using Robust.Shared.Collections;

namespace Content.Server._Classic.Station;

/// <summary>
/// Bounds background generation of planetary terrain. Chunks containing viewers are
/// generated immediately; the rest of the view range is filled from nearest to farthest.
/// </summary>
[RegisterComponent, Access(typeof(BiomeSystem))]
public sealed partial class ClassicBiomeStreamingComponent : Component
{
    /// <summary>
    /// Maximum number of background load slices (and complete chunk unloads) attempted per tick.
    /// The shared wall-clock budget may stop work earlier.
    /// </summary>
    [DataField]
    public int BackgroundChunksPerTick = 4;

    /// <summary>
    /// Hard upper bound on the number of cells generated by one background load operation.
    /// Keeping this below a full chunk bounds the unavoidable overshoot of the soft time budget.
    /// </summary>
    [DataField]
    public int BackgroundCellsPerSlice = 4;

    /// <summary>
    /// Cells around the attached physical viewer that are materialized before physics. A radius of one bounds
    /// a cold foreground miss to 3x3 cells while covering ordinary movement into the next cell.
    /// </summary>
    [DataField]
    public int ViewerSafetyRadius = 1;

    /// <summary>
    /// Number of upcoming physics ticks covered by the attached body's relative-velocity sweep.
    /// </summary>
    [DataField]
    public int ViewerPredictionTicks = 2;

    /// <summary>
    /// Small metre-space expansion covering numerical contact edges and one tick of ordinary
    /// mover acceleration, which is applied later inside the physics update.
    /// </summary>
    [DataField]
    public float ViewerSafetyMargin = 0.05f;

    /// <summary>
    /// Hard upper bound on the number of cells inspected and removed by one unload operation.
    /// Entity default-state comparison is substantially more expensive than clearing the tiles.
    /// </summary>
    [DataField]
    public int UnloadEntitiesPerSlice = 8;

    /// <summary>Maximum precomputed marker nodes spawned by one background operation.</summary>
    [DataField]
    public int MarkerNodesPerSlice = 8;

    /// <summary>
    /// Maximum marker-area cells inspected by one background operation. The biome system also
    /// applies a hard ceiling so a misconfigured prototype cannot restore the old 128x128 scan.
    /// </summary>
    [DataField]
    public int MarkerAreaCellsPerSlice = 64;

    /// <summary>
    /// Maximum opening-snapshot cells inspected by one continuation. Opening discovery uses the
    /// uncached per-tile predicate so a cold 8x8 cache fill cannot hide an atomic 64-cell scan.
    /// The biome system also applies a global hard ceiling and the shared wall-clock deadline.
    /// </summary>
    [DataField]
    public int OpeningCellsPerSlice = 64;

    [DataField]
    public TimeSpan UnloadDelay = TimeSpan.FromSeconds(1);

    /// <summary>Keeps a removed Z-eye range resident briefly.</summary>
    [DataField]
    public TimeSpan ZLevelCacheDuration = TimeSpan.FromSeconds(10);

    /// <summary>Maximum cached Z-eye chunks per biome grid.</summary>
    [DataField]
    public int MaxZLevelCachedChunks = 128;

    /// <summary>Lifetime of completed or resumable opening snapshots between eye toggles.</summary>
    [DataField]
    public TimeSpan OpeningCacheDuration = TimeSpan.FromSeconds(10);

    /// <summary>Bounds transient opening snapshots retained by one biome grid.</summary>
    [DataField]
    public int MaxOpeningCacheEntries = 32;

    /// <summary>
    /// Soft server-tick budget shared by all Classic biome loads and unloads. The smallest budget
    /// configured on the active biome grids is used for the global deadline.
    /// </summary>
    [DataField]
    public TimeSpan WorkBudget = TimeSpan.FromMilliseconds(4);

    /// <summary>
    /// First ungenerated cell of each partially loaded chunk. This is serialized because the
    /// already generated tiles and entities are serialized with the biome itself.
    /// </summary>
    [DataField]
    public Dictionary<Vector2i, int> PartialLoads = new();

    /// <summary>
    /// Cells generated ahead of a chunk's sequential cursor for viewer safety. The bitset avoids
    /// repeatedly sampling/spawning sparse non-anchored biome content and survives map saves.
    /// </summary>
    [DataField]
    public Dictionary<Vector2i, ulong> PriorityLoadedCells = new();

    /// <summary>
    /// Cells whose procedural load pipeline has at least written its tile pass. Normally this is
    /// the sequential cursor plus priority cells; the explicit mask also records a background
    /// tile batch that ran ahead of an entity slice when the wall-clock budget expired.
    /// </summary>
    [DataField]
    public Dictionary<Vector2i, ulong> MaterializedCells = new();

    /// <summary>
    /// Incremental unload state. Such chunks are absent from
    /// <see cref="BiomeComponent.LoadedChunks"/> until unloading finishes or is rolled back.
    /// </summary>
    [DataField]
    public Dictionary<Vector2i, ClassicBiomePartialUnloadState> PartialUnloads = new();

    public readonly HashSet<Vector2i> ViewerChunks = new();
    public readonly HashSet<Vector2i> ViewerCells = new();
    /// <summary>
    /// Adjacent-Z chunks retained only for their exact pre-physics landing cells. They must not
    /// enter the render-active set, otherwise the background cursor expands one safety cell into
    /// a complete hidden 8x8 chunk on every neighbouring Z level.
    /// </summary>
    public readonly HashSet<Vector2i> LandingChunks = new();
    public readonly List<Vector2i> ViewerCenters = new();
    public int ViewerCursor;
    public readonly Dictionary<Vector2i, TimeSpan> PendingUnloads = new();

    /// <summary>Runtime expiry for cached Z-eye chunks.</summary>
    public readonly Dictionary<Vector2i, TimeSpan> CachedZChunks = new();

    /// <summary>
    /// Active render chunks from the previous collection pass. Comparing this bounded set with
    /// the current one discovers chunks that just became inactive without rescanning every
    /// resident procedural chunk on every server tick.
    /// </summary>
    public readonly HashSet<Vector2i> PreviousActiveChunks = new();

    /// <summary>
    /// Runtime tracking starts with one reconciliation of loaded/deserialized state; subsequent
    /// unload discovery is transition-based through <see cref="PreviousActiveChunks"/>.
    /// </summary>
    public bool UnloadTrackingInitialized;

    /// <summary>
    /// Read-only marker discovery has no externally visible effects until it completes, so this
    /// scratch snapshot deliberately is not serialized. A save/reload safely restarts the scan.
    /// </summary>
    public ClassicBiomeMarkerAreaScanState? MarkerAreaScan;

    /// <summary>
    /// Read-only opening snapshots keyed by their integer tile request. Multiple deeper Z-eyes
    /// commonly ask the same upper level about the same viewport; sharing avoids scanning it once
    /// per depth. They are transient and conservative until complete.
    /// </summary>
    public readonly Dictionary<ClassicBiomeOpeningScanKey, ClassicBiomeOpeningScanState> OpeningScans = new();

    /// <summary>
    /// Incremented once per viewer-range collection pass. Scans stamp themselves when requested;
    /// unstamped entries can then be pruned without losing continuations that are still visible.
    /// </summary>
    public int OpeningScanGeneration;
}

public readonly record struct ClassicBiomeOpeningScanKey(
    Vector2i RequiredFirstChunk,
    Vector2i RequiredLastChunk,
    Vector2i FirstTile,
    Vector2i LastTile);

/// <summary>
/// Resumable, read-only snapshot of the procedural opening tiles relevant to one lower Z-eye.
/// Required chunks are verified first, then the padded tile rectangle is scanned one cell at a
/// time. Consumers must remain conservative (hidden) until <see cref="Phase"/> is complete.
/// </summary>
public sealed class ClassicBiomeOpeningScanState
{
    /// <summary>Inclusive unpadded chunk-index range that must be fully materialized.</summary>
    public readonly Vector2i RequiredFirstChunk;
    public readonly Vector2i RequiredLastChunk;

    /// <summary>Inclusive, renderer-guarded tile range whose openings are snapshotted.</summary>
    public readonly Vector2i FirstTile;
    public readonly Vector2i LastTile;

    /// <summary>Current row-major cursors. Their active meaning is selected by <see cref="Phase"/>.</summary>
    public Vector2i NextChunk;
    public Vector2i NextTile;

    /// <summary>
    /// Opening-cache revision at which scanning began. Any mismatch invalidates the partial or
    /// completed result, including multiple tile writes made during one simulation tick.
    /// </summary>
    public ulong Revision;

    public ClassicBiomeOpeningScanPhase Phase;
    public bool HasOpening;
    public Vector2i FirstOpeningTile = new(int.MaxValue, int.MaxValue);
    public Vector2i LastOpeningTile = new(int.MinValue, int.MinValue);

    /// <summary>Collection generation in which this request was most recently observed.</summary>
    public int LastRequestGeneration;

    /// <summary>Simulation time at which a matching Z-eye last requested this snapshot.</summary>
    public TimeSpan LastRequestTime;

    public ClassicBiomeOpeningScanState(
        Vector2i requiredFirstChunk,
        Vector2i requiredLastChunk,
        Vector2i firstTile,
        Vector2i lastTile,
        ulong revision,
        int requestGeneration,
        TimeSpan requestTime)
    {
        RequiredFirstChunk = requiredFirstChunk;
        RequiredLastChunk = requiredLastChunk;
        FirstTile = firstTile;
        LastTile = lastTile;
        NextChunk = requiredFirstChunk;
        NextTile = firstTile;
        Revision = revision;
        LastRequestGeneration = requestGeneration;
        LastRequestTime = requestTime;
    }

    /// <summary>True when an existing continuation describes exactly the current tile request.</summary>
    public bool Matches(
        Vector2i requiredFirstChunk,
        Vector2i requiredLastChunk,
        Vector2i firstTile,
        Vector2i lastTile)
    {
        return RequiredFirstChunk == requiredFirstChunk &&
               RequiredLastChunk == requiredLastChunk &&
               FirstTile == firstTile &&
               LastTile == lastTile;
    }
}

public enum ClassicBiomeOpeningScanPhase : byte
{
    WaitingForChunks,
    Scanning,
    Complete,
}

/// <summary>
/// Deterministic row-major snapshot used while a large Classic marker area is inspected over
/// multiple ticks. Random selection starts only after the snapshot is complete.
/// </summary>
public sealed class ClassicBiomeMarkerAreaScanState
{
    public readonly string Layer;
    public readonly Vector2i MarkerChunk;
    public readonly bool Forced;
    public readonly Box2i Bounds;
    public readonly int Count;
    public readonly int MarkerSeed;
    public readonly Random Random;
    public ClassicBiomeMarkerAreaScanPhase Phase;
    public int NextCell;
    public readonly HashSet<Vector2i> RemainingTiles = new();
    public readonly Dictionary<Vector2i, EntityUid?> NodeEntities = new();
    public readonly Dictionary<Vector2i, string?> NodeMasks = new();
    public readonly Dictionary<Vector2i, EntityUid> ReplaceableEntities = new();
    public ValueList<Vector2i> Frontier = new(32);
    public int GroupIndex;
    public int GroupRemaining;
    public bool GroupStarted;
    public bool SeedPickActive;
    public int SeedPickTarget;
    public int SeedPickCursor;
    public HashSet<Vector2i>.Enumerator SeedEnumerator;
    public readonly HashSet<EntityUid> EntitiesToDelete = new();
    public readonly Dictionary<Vector2i, Dictionary<string, List<Vector2i>>> PendingMarkers = new();

    public ClassicBiomeMarkerAreaScanState(
        string layer,
        Vector2i markerChunk,
        bool forced,
        Box2i bounds,
        int count,
        int markerSeed)
    {
        Layer = layer;
        MarkerChunk = markerChunk;
        Forced = forced;
        Bounds = bounds;
        Count = count;
        MarkerSeed = markerSeed;
        Random = new Random(markerSeed);
    }
}

public enum ClassicBiomeMarkerAreaScanPhase : byte
{
    Scanning,
    Selecting,
}

[DataDefinition]
public sealed partial class ClassicBiomePartialUnloadState
{
    [DataField]
    public ClassicBiomePartialUnloadPhase Phase;

    /// <summary>
    /// Procedural entities already deleted from otherwise still-loaded cells. This permits an
    /// active/viewer chunk to roll the unload back without touching unprocessed entities.
    /// </summary>
    [DataField]
    public HashSet<Vector2i> RemovedEntityCells = new();

    /// <summary>
    /// True when teardown began before the chunk reached LoadedChunks. On rollback the original
    /// cursor is restored instead of falsely promoting an incomplete chunk to complete.
    /// </summary>
    [DataField]
    public bool WasPartial;

    [DataField]
    public int PartialCursor;

    [DataField]
    public ulong PriorityCells;

    /// <summary>
    /// Cells that actually reached the procedural load pipeline before teardown began. Partial
    /// chunks must finalize only these cells; treating all 64 as loaded creates false modified
    /// tiles and permanent holes when the chunk is visited again.
    /// </summary>
    [DataField]
    public ulong MaterializedCells;

    /// <summary>
    /// First cell not yet classified for tile teardown. Classification is read-only and can be
    /// resumed safely; physical tiles are committed only after the whole snapshot is ready.
    /// </summary>
    [DataField]
    public int FinalizeCursor;

    /// <summary>
    /// Materialized cells proven to still contain their unmodified procedural tile. The commit
    /// phase rechecks modifications and anchored entities before clearing these cells.
    /// </summary>
    [DataField]
    public ulong ClearableCells;
}

public enum ClassicBiomePartialUnloadPhase : byte
{
    Entities,
    Finalize,
    Restoring,
    // Appended to preserve the serialized numeric value of Restoring in existing saves.
    Commit,
}
