using Content.Shared._Classic.Vendors;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Classic.Vendors;

[GenerateTypedNameReferences]
public sealed partial class ClassicAutomatedVendorSection : Control
{
    public ClassicVendorSection? Section;

    public ClassicAutomatedVendorSection()
    {
        RobustXamlLoader.Load(this);
    }
}


