using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Classic.Vendors;

[GenerateTypedNameReferences]
public sealed partial class ClassicAutomatedVendorEntry : Control
{
    public ClassicAutomatedVendorEntry()
    {
        RobustXamlLoader.Load(this);
    }
}


