using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Classic.Vendors;

[GenerateTypedNameReferences]
public sealed partial class ClassicAutomatedVendorWindow : DefaultWindow
{
    public ClassicAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
    }
}


