using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Classic.Vendors;

[GenerateTypedNameReferences]
public sealed partial class ClassicAutomatedVendorButton : Button
{
    public event Action? OnDrawModeChanged;

    public ClassicAutomatedVendorButton()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}


