# PMC Antag Prototypes
- type: antag
  id: PMCAssault
  name: Eridani PMC (Assault)
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 48h
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 1h
  - !type:RoleTimeRequirement
    role: JobSalvageSpecialist
    time: 3h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 4h
  - !type:RoleTimeRequirement
    role: AntagTraitor
    time: 1h
  guides: [ NuclearOperatives ]
  playTimeTracker: AntagNukeops

- type: antag
  id: PMCSpecialist
  name: Eridani PMC (Specialist)
  objective: nukeops-role-objective
  antagonist: true
  setPreference: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 48h
  guides: [ NuclearOperatives ]
  playTimeTracker: AntagNukeops

- type: antag
  id: PMCMedic
  name: Eridani PMC (Medic)
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 48h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 6h
  - !type:RoleTimeRequirement
    role: JobSurgeon
    time: 3h
  - !type:RoleTimeRequirement
    role: JobBrigmedic
    time: 3h
  - !type:RoleTimeRequirement
    role: AntagTraitor
    time: 1h
  guides: [ NuclearOperatives ]
  playTimeTracker: AntagNukeopsMedic

- type: antag
  id: PMCCommander
  name: Eridani PMC (Commander)
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 72h
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Command
    time: 10h
  - !type:RoleTimeRequirement
    role: AntagNukeops
    time: 1800
  guides: [ NuclearOperatives ]
  playTimeTracker: AntagNukeopsCommander

- type: antagSpecifier
  abstract: true
  parent: RestrictedAntag
  id: BasePMC
  prefRoles:
  - GenericTeamAntagonist
  allowNonHumans: true
  tags:
  - CantBecomeRevolutionary
  components:
  - type: NukeOperative
  - type: NpcFactionMember
    factions:
    - Syndicate

- type: antagSpecifier
  parent: BasePMC
  id: PMCCommander
  prefRoles:
  - PMCCommander
  spawnerPrototype: SpawnPointPMCCommander
  components:
  - type: PMCCommander
  - type: ClassicVendorUser
    points: 100
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-pmc-commander
  mindRoles:
  - MindRoleNukeopsCommander

- type: antagSpecifier
  parent: BasePMC
  id: PMCMedic
  prefRoles:
  - PMCMedic
  spawnerPrototype: SpawnPointPMCMedic
  components:
  - type: PMCMedic
  - type: ClassicVendorUser
    points: 50
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-pmc-medic
  mindRoles:
  - MindRoleNukeopsMedic

- type: antagSpecifier
  parent: BasePMC
  id: PMCSpecialist
  prefRoles:
  - PMCSpecialist
  spawnerPrototype: SpawnPointPMCSpecialist
  components:
  - type: PMCSpecialist
  - type: ClassicVendorUser
    points: 50
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-pmc-specialist
  mindRoles:
  - MindRoleNukeops

- type: antagSpecifier
  parent: BasePMC
  id: PMCAssault
  prefRoles:
  - PMCAssault
  spawnerPrototype: SpawnPointPMCAssault
  components:
  - type: PMCAssault
  - type: ClassicVendorUser
    points: 50
  - type: RandomMetadata
    nameSegments:
    - NamesSyndicateNormal
    nameFormat: name-format-pmc-assault
  mindRoles:
  - MindRoleNukeops
